objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Res_Center_Booking_Office__c</fullName>
        <label>Res Center / Booking Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aberdeen Scotland</fullName>
                </value>
                <value>
                    <fullName>Ancaster Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Avenir</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Burlington Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Burlington VT</fullName>
                </value>
                <value>
                    <fullName>Calgary Alberta Canada</fullName>
                </value>
                <value>
                    <fullName>Cambridge MA</fullName>
                </value>
                <value>
                    <fullName>Chicago - Schaumburg</fullName>
                </value>
                <value>
                    <fullName>Cleveland OH</fullName>
                </value>
                <value>
                    <fullName>Cleveland West</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Edinburgh Scotland</fullName>
                </value>
                <value>
                    <fullName>Edmonton Alberta Canada</fullName>
                </value>
                <value>
                    <fullName>Evansville IN</fullName>
                </value>
                <value>
                    <fullName>Georgetown Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Greenville</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Houston West</fullName>
                </value>
                <value>
                    <fullName>ILMO Bloomington</fullName>
                </value>
                <value>
                    <fullName>Kamloops British Columbia Canada</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Mequon WI</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Minneapolis-Blue</fullName>
                </value>
                <value>
                    <fullName>Minneapolis-ORD/NavyPier</fullName>
                </value>
                <value>
                    <fullName>Mississauga Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Montreal Quebec Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Res_Center_Booking_Office__c</fullName>
        <description>The res center/booking office for a Case is populated from the related Account, when a Client Traveler Survey Case record is autogenerated through flow.</description>
        <label>Res Center / Booking Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <description>Custom Survey_Question__c object that allows more customization than the native Salesforce Surveys solution. The Survey Question object represents an instance of a question that is presented to a survey respondent as part of a Survey. Every Survey Question record relates to a Survey record.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the survey question.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>RadioButton</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>ShortText</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Question_Text__c</fullName>
        <description>The name of the Survey Question record is truncated at 255 characters. This field stores the full question text, up to 32,768 characters. This is the text that should be displayed to the end survey respondent when taking a survey.</description>
        <label>Full Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Survey_Question_Response__c.object
<CustomObject>
    <description>Custom object built as part of a solution to deliver functionality beyond native Salesforce Surveys. Survey Question Responses relate to Survey_Question__c records, which in turn relate to a Survey__c record. This object specifically stores the responses submitted for a survey.</description>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000000000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Data_Type__c</fullName>
        <description>The data type of the question response</description>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Int</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <description>Response provided by a participant for a question.</description>
        <label>Text Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <description>Response provided by a participant for the following question types:
Net Promoter Score (NPS)
Rating
Score
Slider</description>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Lookup to the Survey Question this record is in response to.</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Survey_Question_To_Case_Mapping__mdt.object
<CustomObject>
    <description>Traveler Survey Question To Case Mappings</description>
    <label>Survey Question To Case Mapping</label>
    <pluralLabel>Survey Question To Case Mappings</pluralLabel>
    <fields>
        <fullName>Case_Field__c</fullName>
        <description>Case field Field Name</description>
        <label>Case Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question_Name__c</fullName>
        <description>Name of survey question</description>
        <label>Survey Question Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/MapSurveyQuestionToCaseInvocableApex.cls
/**
 * @author Samuel Prada, Rosetree Solutions
 * @website https://rosetreesolutions.com/
 * @email info@RosetreeSolutions.com
 * @phone (214) 731 - 7314
 * @date 06/04/23
 * @Description This is a class containing an invocable Apex method used for 
 * the mapping of Case fields triggered by SurveyResponse creation. 
 */

 /**
 * @Description This is a class containing an invocable Apex method used for 
 * the mapping of Case fields triggered by SurveyResponse creation. 
 */
public without sharing class MapSurveyQuestionToCaseInvocableApex {

    /**
    * @Description This method creates a shell Case with some fields mapped to it from Survey_Question_Response__c objects
    * and also creates a String to be mapped to the Subject field on Case.
    * @param arguments List<Arguments>   
    * @return List<Results>         
    */
    @InvocableMethod(Label='Populate shell Case and create Subject string')
    public static List<Results> mapSurveyQuestionsToCase(List<Arguments> arguments) {
        List<Survey_Question__c> surveyQuestionList = arguments.get(0).surveyQuestionList;
        Map<Id, Survey_Question__c> surveyQuestionsMap = new Map<Id, Survey_Question__c>(); 
        for (Survey_Question__c question : surveyQuestionList) {
            surveyQuestionsMap.put(question.Id, question);
        }

        Map<String, Survey_Question_Response__c> questionNameToSurveyQuestionResponse = new Map<String, Survey_Question_Response__c>();
        List<Survey_Question_Response__c> questionResponses = arguments.get(0).questionResponses;

        for (Survey_Question_Response__c sqr : questionResponses) {
            Survey_Question__c sq = surveyQuestionsMap.get(sqr.Survey_Question__c);
            questionNameToSurveyQuestionResponse.put(sq.Full_Question_Text__c, sqr);
        }

        Map<String, String> questionToFieldMap = new Map<String, String>();
        for (Survey_Question_To_Case_Mapping__mdt record : Survey_Question_To_Case_Mapping__mdt.getAll().values()) {
            questionToFieldMap.put(record.Survey_Question_Name__c, record.Case_Field__c);
        }

        Account account = [SELECT Name, Res_Center_Booking_Office__c FROM Account WHERE Id =: arguments.get(0).accountId];
        Case newCase = new Case(
            Subject = account.Res_Center_Booking_Office__c + ' ' + account.Name + ' Low Net Promoter Score'
        );
        for (String questionName : questionNameToSurveyQuestionResponse.keySet()) {

            //If Case field is not mapped, skip to next value
            if(questionToFieldMap.get(questionName) == null){
                continue;
            }

            Survey_Question_Response__c sqr = questionNameToSurveyQuestionResponse.get(questionName);
            String questionType = surveyQuestionsMap.get(sqr.Survey_Question__c).Question_Type__c;
            String responseDataType = sqr.Data_Type__c;

            if(questionType == 'NPS'){
                newCase.put(questionToFieldMap.get(questionName), questionNameToSurveyQuestionResponse.get(questionName).Number_Value__c);
            } else {
                newCase.put(questionToFieldMap.get(questionName), questionNameToSurveyQuestionResponse.get(questionName).Text_Value__c);
            }
        }

        Results response = new Results();
        response.outputCase = newCase;
        List<Results> responseWrapper= new List<Results>();
        responseWrapper.add(response);
        
        return responseWrapper;
    }

    /**
    * @Description This inner class is a wrapper for the invocable apex's input parameters       
    */
    public class Arguments {
        @InvocableVariable(Label='AccountId' Description='Account Id to map to Case OwnerId' Required=true)
        public String accountId;
        @InvocableVariable(Label='Survey_Question_Response__c List' Description='List of Survey_Question_Response__c records' Required=true)
        public List<Survey_Question_Response__c> questionResponses;
        @InvocableVariable(Label='Survey_Question__c List' Description='List of Survey_Question__c records' Required=true)
        public List<Survey_Question__c> surveyQuestionList;
    }

    /**
    * @Description This inner class is a wrapper for the invocable apex's output parameters       
    */
    public class Results {
        @InvocableVariable(Label='Case for Output' Description='Mapped Case' Required=true)
        public Case outputCase;
    }
}