objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RegionG</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <description>Custom survey object built to expand functionality beyond the native Salesforce Survey model.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description of Survey__c record.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Survey_Invitation__c.object
<CustomObject>
    <description>Custom Survey Invitation object designed to replace the native Salesforce Surveys SurveyInvitation object. Survey Invitations represent an instance of a survey generated and sent to a user (via URL) to take.</description>
    <label>Survey Invitation</label>
    <nameField>
        <label>Survey Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey__c record in use for this Survey Invitation.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account record related to the survey respondent for this Survey Invitation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Id__c</fullName>
        <description>Id of the Experience Cloud Site that the Survey Invitation was generated from.</description>
        <label>Community Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CreateSurveyLWC_Controller_Test.cls
//Objects associated with Surveys are not writeable and seeAllData=true must be used.
@IsTest(SeeAllData=true)
public class CreateSurveyLWC_Controller_Test {

    static void setup() {
        List<Survey__c> clientTravelerSurvey = [SELECT Id FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];

        if(clientTravelerSurvey.size() == 0) {
            // Create a Survey record
            Survey__c survey = new Survey__c(
                    Name = 'Client Traveler Survey',
                    Developer_Name__c = 'client_traveler_survey',
                    Description__c = 'A survey to gauge customer satisfaction.'
            );
            insert survey;
        }

    }

	@IsTest
    static void createSurveySuccessTest() {
        setup();
        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;
        
        Survey__c survey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(survey.Id != null);
        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
		Test.startTest();
        	String surveyURL = CreateSurveyLWC_Controller.createSurvey(testAccount.Id, survey.Developer_Name__c, community.Id, 'en');
        Test.stopTest();
        
        Survey_Invitation__c createdInvitation = [SELECT Id, Account__c, Survey__c, Community_Id__c FROM Survey_Invitation__c WHERE Account__c =: testAccount.Id];
        System.assert(createdInvitation.Id != null);
        System.assert(createdInvitation.Community_Id__c == community.Id);
        System.assert(createdInvitation.Survey__c == survey.Id);
    }

    @IsTest
    static void testCreateSurveyNoAccountId() {
        setup();

        Survey__c survey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(survey.Id != null);
        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);

        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(null, survey.Developer_Name__c, community.Id, 'en');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Parameter \'accountId\' can not be null.', 
            actualException.getMessage()
        );
    }

    @IsTest
    static void testCreateSurveyNoSurveyName() {
        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;

        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(testAccount.Id, null, community.Id, 'en');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Parameter \'surveyName\' can not be null.', 
            actualException.getMessage()
        );
    }

    @IsTest
    static void testCreateSurveyNoCommunityId() {
        setup();

        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;

        Survey__c testSurvey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(testSurvey.Id != null);

        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(testAccount.Id, testSurvey.Developer_Name__c, null, 'en');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Parameter \'communityId\' can not be null.', 
            actualException.getMessage()
        );    
    }

    @IsTest
    static void testCreateSurveyNoLanguageParameter() {
        setup();

        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;

        Survey__c survey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(survey.Id != null);
        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(testAccount.Id, survey.Developer_Name__c, community.Id, null);
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Parameter \'language\' can not be null.', 
            actualException.getMessage()
        );
    }

    @IsTest
    static void testCreateSurveyInvalidSurveyName() {
        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;

        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(testAccount.Id, 'testDummyBadParameter', community.Id, 'en');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Invalid Survey name.',
            actualException.getMessage()
        );
    }

    @IsTest
    static void testCreateSurveyInvalidAccountId() {
        setup();

        Survey__c survey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(survey.Id != null);
        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey('INVALIDID', survey.Developer_Name__c, community.Id, 'en');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Invalid Account Id.', 
            actualException.getMessage()
        );
    }

    @IsTest
    static void testCreateSurveyInvalidLanguageParameter() {
        setup();

        Account testAccount = new Account(
        	Name = 'Test Account',
            Region__c = 'East'
        );
        insert testAccount;

        Survey__c survey = [SELECT Id, Developer_Name__c, Name FROM Survey__c WHERE Developer_Name__c = 'client_traveler_survey' LIMIT 1];
        System.assert(survey.Id != null);
        Network community = [SELECT Id, UrlPathPrefix FROM Network WHERE UrlPathPrefix = 'ENGSurvey'];
		System.assert(community.Id != null);
        
        Test.startTest();
        Exception actualException;
        try {
            CreateSurveyLWC_Controller.createSurvey(testAccount.Id, survey.Developer_Name__c, community.Id, 't');
        } catch(Exception e) {
            actualException = e;
        }
        Test.stopTest();

        System.assert(
            actualException instanceof CreateSurveyLWC_Controller.InvalidParameterException, 
            'Exception type should be InvalidParameterException'
        );
        System.assertEquals(
            'Invalid language parameter.', 
            actualException.getMessage()
        );
    }
}