objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <description>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</description>
        <inlineHelpText>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</inlineHelpText>
        <label>Reported Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2019 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2018 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2017 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2016 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2015 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2014 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2013 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2012 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2011 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2010 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2009 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2007 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2007 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2020 - Calendar Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Travel_Volume__c.object
<CustomObject>
    <description>Stores the account travel volumes from back office</description>
    <label>Travel Volume</label>
    <nameField>
        <displayFormat>TV-{0000000}</displayFormat>
        <label>Travel Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Trip</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Avenir</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Volumes</relationshipLabel>
        <relationshipName>Travel_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <label>Reported Year</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reported_Month__c</fullName>
        <label>Reported Month</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Day_of_Month__c</fullName>
        <label>First Day of Month</label>
        <type>Date</type>
    </fields>
</CustomObject>

classes/Batch_MonthlyTravelVolume.cls
global class Batch_MonthlyTravelVolume implements Database.Batchable<SObject> {

    Date currentDate;
    String myMonth;
    String myYear;
    Date firstDayOfMonth;

    global Batch_MonthlyTravelVolume() {
        currentDate = Date.today();  // For current month
        Integer fullMonth = currentDate.month() + 100;
        myMonth = String.valueOf(fullMonth).right(2);
        myYear = String.valueOf(currentDate.year());
        firstDayOfMonth = Date.newInstance(currentDate.year(), currentDate.month(), 1);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id
            FROM Account
        ]);
    }

    global void execute(Database.BatchableContext bc, List<Account> scope) {
        Set<Id> accountIds = new Set<Id>();
        for (Account acct : scope) {
            accountIds.add(acct.Id);
        }

        // Step 1: Query existing Travel Volume records for the current month/year
        Map<String, Boolean> existingKeys = new Map<String, Boolean>();
        for (Travel_Volume__c tv : [
            SELECT Account__c, Type__c
            FROM Travel_Volume__c
            WHERE Account__c IN :accountIds
            AND Reported_Month__c = :myMonth
            AND Reported_Year__c = :myYear
        ]) {
            String key = tv.Type__c + '-' + tv.Account__c;
            existingKeys.put(key, true);
        }

        // Step 2: Only add if record doesn't already exist
        List<Travel_Volume__c> objectList = new List<Travel_Volume__c>();
        for (Account account : scope) {
            for (String type : new List<String>{'Core', 'Avenir'}) {
                String key = type + '-' + account.Id;
                if (!existingKeys.containsKey(key)) {
                    objectList.add(new Travel_Volume__c(
                        Account__c = account.Id,
                        Reported_Month__c = myMonth,
                        Reported_Year__c = myYear,
                        First_Day_of_Month__c = firstDayOfMonth,
                        Type__c = type
                    ));
                }
            }
        }

        if (!objectList.isEmpty()) {
            insert objectList;
        }
    }

    global void finish(Database.BatchableContext bc) {
        // Optional: Add logging or notifications if needed
    }
}