objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RegionG</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Car_Spend__c</fullName>
        <label>Car Spend (Prev Yr)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Spend__c</fullName>
        <label>Hotel Spend (Prev Yr)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <description>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</description>
        <inlineHelpText>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</inlineHelpText>
        <label>Reported Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2019 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2018 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2017 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2016 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2015 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2014 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2013 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2012 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2011 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2010 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2009 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2007 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2007 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2020 - Calendar Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Air_Spend_Total__c</fullName>
        <label>Air Spend-Total (Prev Yr)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Account_Number__c.object
<CustomObject>
    <label>Account Number</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Account Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Numbers</relationshipLabel>
        <relationshipName>Account_Number</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/DK_Volume__c.object
<CustomObject>
    <label>DK Travel Volume</label>
    <nameField>
        <displayFormat>DK-{00000000}</displayFormat>
        <label>DK Volume</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DK Travel Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Trip</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Avenir</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Travel_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Car_Spend__c</fullName>
        <label>Car Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Spend__c</fullName>
        <label>Hotel Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Trips__c</fullName>
        <description>This represents total Avenir Trip Total for a defined period.</description>
        <label>Total Trips</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <label>Reported Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Volume__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Travel Volume</label>
        <referenceTo>Travel_Volume__c</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Travel_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number Name</label>
        <referenceTo>Account_Number__c</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reported_Month__c</fullName>
        <label>Reported Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Air_Spend_Total__c</fullName>
        <label>Air Spend-Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Travel_Volume__c.object
<CustomObject>
    <description>Stores the account travel volumes from back office</description>
    <label>Travel Volume</label>
    <nameField>
        <displayFormat>TV-{0000000}</displayFormat>
        <label>Travel Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Trip</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Avenir</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Volumes</relationshipLabel>
        <relationshipName>Travel_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Car_Spend__c</fullName>
        <label>Car Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Spend__c</fullName>
        <label>Hotel Spend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Trips__c</fullName>
        <description>This represents total Avenir Trip Total for a defined period.</description>
        <label>Total Trips</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <label>Reported Year</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reported_Month__c</fullName>
        <label>Reported Month</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Air_Spend_Total__c</fullName>
        <label>Air Spend-Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/DKTravelVolumeTriggerHandlerTest.cls
@isTest
private class DKTravelVolumeTriggerHandlerTest {

    @testSetup
    static void setupTestData() {
        // Create Account
        Account acc = new Account(Name = 'Test Account', Region__c = 'Canada West');
        insert acc;

        // Create Account Number
        Account_Number__c accNumber = new Account_Number__c(Account__c = acc.Id, Account_Number__c = '1234567');
        insert accNumber;

        // Define common month and year
        String month = '06';
        String year = '2025';

        // Create Travel Volume for Avenir and Core
        Travel_Volume__c tvAvenir = new Travel_Volume__c(
            Account__c = acc.Id,
            Reported_Month__c = month,
            Reported_Year__c = year,
            Type__c = 'Avenir'
        );
        Travel_Volume__c tvCore = new Travel_Volume__c(
            Account__c = acc.Id,
            Reported_Month__c = month,
            Reported_Year__c = year,
            Type__c = 'Core'
        );
        insert new List<Travel_Volume__c>{ tvAvenir, tvCore };

        // DK Volumes (Avenir)
        List<DK_Volume__c> avenirDKs = new List<DK_Volume__c>{
            new DK_Volume__c(
                Account__c = acc.Id,
                Account_Number__c = accNumber.Id,
                Reported_Month__c = month,
                Reported_Year__c = year,
                Type__c = 'Avenir',
                Air_Spend_Total__c = 100,
                Car_Spend__c = 50,
                Hotel_Spend__c = 75,
                Total_Trips__c = 10
            ),
            new DK_Volume__c(
                Account__c = acc.Id,
                Account_Number__c = accNumber.Id,
                Reported_Month__c = month,
                Reported_Year__c = year,
                Type__c = 'Avenir',
                Air_Spend_Total__c = 200,
                Car_Spend__c = 80,
                Hotel_Spend__c = 125,
                Total_Trips__c = 20
            )
        };

        // DK Volumes (Core)
        List<DK_Volume__c> coreDKs = new List<DK_Volume__c>{
            new DK_Volume__c(
                Account__c = acc.Id,
                Account_Number__c = accNumber.Id,
                Reported_Month__c = month,
                Reported_Year__c = year,
                Type__c = 'Core',
                Air_Spend_Total__c = 150,
                Car_Spend__c = 60,
                Hotel_Spend__c = 90,
                Total_Trips__c = 5
            )
        };

        insert avenirDKs;
        insert coreDKs;
    }

    @isTest
    static void testAfterInsertRollupByType() {
        // Avenir Travel Volume
        Travel_Volume__c tvAvenir = [
            SELECT Air_Spend_Total__c, Car_Spend__c, Hotel_Spend__c, Total_Trips__c 
            FROM Travel_Volume__c 
            WHERE Type__c = 'Avenir' 
            LIMIT 1
        ];

        // Core Travel Volume
        Travel_Volume__c tvCore = [
            SELECT Air_Spend_Total__c, Car_Spend__c, Hotel_Spend__c, Total_Trips__c 
            FROM Travel_Volume__c 
            WHERE Type__c = 'Core' 
            LIMIT 1
        ];
    }

    @isTest
    static void testAfterDeleteRollupUpdate() {
        // Delete one Avenir DK record
        DK_Volume__c dkvToDelete = [SELECT Id FROM DK_Volume__c WHERE Type__c = 'Avenir' LIMIT 1];
        delete dkvToDelete;

        // Validate recalculation for Avenir
        Travel_Volume__c tvAvenir = [
            SELECT Air_Spend_Total__c, Car_Spend__c, Hotel_Spend__c, Total_Trips__c 
            FROM Travel_Volume__c 
            WHERE Type__c = 'Avenir' 
            LIMIT 1
        ];
    }

    @isTest
    static void testUpdateTravelVolumeMapping() {
        // Create Account
        Account acc = new Account(Name = 'Mapping Test Account', Region__c = 'Canada East');
        insert acc;

        // Create Account Number
        Account_Number__c accNumber = new Account_Number__c(Account__c = acc.Id, Account_Number__c = 'AN-9999999');
        insert accNumber;

        // Month and Year for formula-based MatchID
        String month = '05';
        String year = '2024';

        // Create matching Travel Volume record
        Travel_Volume__c tv = new Travel_Volume__c(
            Account__c = acc.Id,
            Reported_Month__c = month,
            Reported_Year__c = year,
            Type__c = 'Core'
        );
        insert tv;

        // Create DK Volume with required Account Number
        DK_Volume__c dkv = new DK_Volume__c(
            Account__c = acc.Id,
            Account_Number__c = accNumber.Id,
            Reported_Month__c = month,
            Reported_Year__c = year,
            Type__c = 'Core'
        );
        insert dkv;

        // Verify mapping occurred
        DK_Volume__c updated = [SELECT Travel_Volume__c FROM DK_Volume__c WHERE Id = :dkv.Id];
    }
}