objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RegionG</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Res_Center_Booking_Office__c</fullName>
        <label>Res Center / Booking Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aberdeen Scotland</fullName>
                </value>
                <value>
                    <fullName>Ancaster Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Avenir</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Burlington Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Burlington VT</fullName>
                </value>
                <value>
                    <fullName>Calgary Alberta Canada</fullName>
                </value>
                <value>
                    <fullName>Cambridge MA</fullName>
                </value>
                <value>
                    <fullName>Chicago - Schaumburg</fullName>
                </value>
                <value>
                    <fullName>Cleveland OH</fullName>
                </value>
                <value>
                    <fullName>Cleveland West</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Edinburgh Scotland</fullName>
                </value>
                <value>
                    <fullName>Edmonton Alberta Canada</fullName>
                </value>
                <value>
                    <fullName>Evansville IN</fullName>
                </value>
                <value>
                    <fullName>Georgetown Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Greenville</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Houston West</fullName>
                </value>
                <value>
                    <fullName>ILMO Bloomington</fullName>
                </value>
                <value>
                    <fullName>Kamloops British Columbia Canada</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Mequon WI</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Minneapolis-Blue</fullName>
                </value>
                <value>
                    <fullName>Minneapolis-ORD/NavyPier</fullName>
                </value>
                <value>
                    <fullName>Mississauga Ontario Canada</fullName>
                </value>
                <value>
                    <fullName>Montreal Quebec Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <description>Custom Survey_Question__c object that allows more customization than the native Salesforce Surveys solution. The Survey Question object represents an instance of a question that is presented to a survey respondent as part of a Survey. Every Survey Question record relates to a Survey record.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the survey question.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>RadioButton</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>ShortText</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Question_Text__c</fullName>
        <description>The name of the Survey Question record is truncated at 255 characters. This field stores the full question text, up to 32,768 characters. This is the text that should be displayed to the end survey respondent when taking a survey.</description>
        <label>Full Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Survey_Question_Response__c.object
<CustomObject>
    <description>Custom object built as part of a solution to deliver functionality beyond native Salesforce Surveys. Survey Question Responses relate to Survey_Question__c records, which in turn relate to a Survey__c record. This object specifically stores the responses submitted for a survey.</description>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000000000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Text_Value__c</fullName>
        <description>Response provided by a participant for a question.</description>
        <label>Text Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <description>Response provided by a participant for the following question types:
Net Promoter Score (NPS)
Rating
Score
Slider</description>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Lookup to the Survey Question this record is in response to.</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

classes/MapSurveyQuestionToCaseApex_Test.cls
@IsTest
private class MapSurveyQuestionToCaseApex_Test {

    @TestSetup 
    static void setup() {
        Account acct = new Account(
            Res_Center_Booking_Office__c = 'San Francisco;Atlanta', Name = 'TestAcct', Region__c = 'East'
        );
        insert acct;
    }

    @IsTest
    static void testMethodResponseCreatedCorrectly(){
        //List<Survey_Question_Response__c> JSON String 
        String sqrListJsonString =  '[{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMJCA2"},' + 
                                    '"Id":"0Kr010000004EMJCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY8CAK","Text_Value__c":"I acknowledge"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMKCA2"},' + 
                                    '"Id":"0Kr010000004EMKCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY4CAK","Number_Value__c":1,"Text_Value__c":"1"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMLCA2"},' +
                                    '"Id":"0Kr010000004EMLCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY6CAK","Text_Value__c":"Mike Masters"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMMCA2"},' +
                                    '"Id":"0Kr010000004EMMCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY5CAK","Text_Value__c":"Nothing"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMNCA2"},' +
                                    '"Id":"0Kr010000004EMNCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY3CAK","Text_Value__c":"Low Score, Email Provided"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMOCA2"},' +
                                    '"Id":"0Kr010000004EMOCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY7CAK","Text_Value__c":"t@t.com"}]';
        //List<Survey_Question__c> JSON String 
        String sqListJsonString =   '[{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY3CAK"},"Id":"0Ku01000000CgY3CAK",' +
                                    '"Full_Question_Text__c":"How was your reservation experience?"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY4CAK"},"Id":"0Ku01000000CgY4CAK",' +
                                    '"Full_Question_Text__c":"How likely are you to recommend our services to a colleague?","Question_Type__c":"NPS"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY5CAK"},"Id":"0Ku01000000CgY5CAK",' +
                                    '"Full_Question_Text__c":"Thank you for taking the time to complete this survey. We truly appreciate your feedback, if there are any other comments you ' +
                                    'would like to add we would love to hear from you."},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY6CAK"},"Id":"0Ku01000000CgY6CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  first and last name below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY7CAK"},"Id":"0Ku01000000CgY7CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  email address below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY8CAK"},"Id":"0Ku01000000CgY8CAK",' +
                                    '"Full_Question_Text__c":"‘Data protection: Direct Travel will never release your personal details to any company outside Direct Travel for mailing or ' +
                                    'marketing purposes. In this instance, personal details are used for the purposes of collecting feedback on the service you received from ' +
                                    'Direct Travel. Please see our privacy policy at  Privacy &#124; Direct Travel (dt.com) .’"}]';
        MapSurveyQuestionToCaseInvocableApex.Arguments arguments = new MapSurveyQuestionToCaseInvocableApex.Arguments();
        Account account = [SELECT Id, Res_Center_Booking_Office__c, Name FROM Account LIMIT 1];
        arguments.accountId = account.Id;
        arguments.surveyQuestionList = (List<Survey_Question__c>) JSON.deserialize(sqListJsonString, List<Survey_Question__c>.class);
        arguments.questionResponses = (List<Survey_Question_Response__c>) JSON.deserialize(sqrListJsonString, List<Survey_Question_Response__c>.class);
        List<MapSurveyQuestionToCaseInvocableApex.Arguments> argumentsWrapper= new List<MapSurveyQuestionToCaseInvocableApex.Arguments>();
        argumentsWrapper.add(arguments);
        

        Test.startTest();
        List<MapSurveyQuestionToCaseInvocableApex.Results> results = MapSurveyQuestionToCaseInvocableApex.mapSurveyQuestionsToCase(argumentsWrapper);
        Test.stopTest();

        System.assertEquals(1, results.get(0).outputCase.How_likely_to_recommend_services__c);
//        System.assertEquals('t@t.com', results.get(0).outputCase.Respondent_Email__c);
//        System.assertEquals('Mike Masters', results.get(0).outputCase.Respondent_Name__c);
//        System.assertEquals('Nothing', results.get(0).outputCase.Other_comments__c);
//        System.assertEquals('Low Score, Email Provided', results.get(0).outputCase.How_was_your_reservation_experience__c);
        System.assertEquals(account.Res_Center_Booking_Office__c + ' ' + account.Name + ' Low Net Promoter Score', results.get(0).outputCase.Subject);
    }

    @IsTest
    static void testNoAccountIdPassedToInvocableMethod(){
        //List<Survey_Question_Response__c> JSON String 
        String sqrListJsonString =  '[{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMJCA2"},' + 
                                    '"Id":"0Kr010000004EMJCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY8CAK","Text_Value__c":"I acknowledge"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMKCA2"},' + 
                                    '"Id":"0Kr010000004EMKCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY4CAK","Number_Value__c":1,"Text_Value__c":"1"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMLCA2"},' +
                                    '"Id":"0Kr010000004EMLCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY6CAK","Text_Value__c":"Mike Masters"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMMCA2"},' +
                                    '"Id":"0Kr010000004EMMCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY5CAK","Text_Value__c":"Nothing"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMNCA2"},' +
                                    '"Id":"0Kr010000004EMNCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY3CAK","Text_Value__c":"Low Score, Email Provided"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMOCA2"},' +
                                    '"Id":"0Kr010000004EMOCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY7CAK","Text_Value__c":"t@t.com"}]';
        //List<Survey_Question__c> JSON String 
        String sqListJsonString =   '[{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY3CAK"},"Id":"0Ku01000000CgY3CAK",' +
                                    '"Full_Question_Text__c":"How was your reservation experience?"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY4CAK"},"Id":"0Ku01000000CgY4CAK",' +
                                    '"Full_Question_Text__c":"How likely are you to recommend our services to a colleague?","Question_Type__c":"NPS"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY5CAK"},"Id":"0Ku01000000CgY5CAK",' +
                                    '"Full_Question_Text__c":"Thank you for taking the time to complete this survey. We truly appreciate your feedback, if there are any other comments you ' +
                                    'would like to add we would love to hear from you."},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY6CAK"},"Id":"0Ku01000000CgY6CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  first and last name below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY7CAK"},"Id":"0Ku01000000CgY7CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  email address below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY8CAK"},"Id":"0Ku01000000CgY8CAK",' +
                                    '"Full_Question_Text__c":"‘Data protection: Direct Travel will never release your personal details to any company outside Direct Travel for mailing or ' +
                                    'marketing purposes. In this instance, personal details are used for the purposes of collecting feedback on the service you received from ' +
                                    'Direct Travel. Please see our privacy policy at  Privacy &#124; Direct Travel (dt.com) .’"}]';
        MapSurveyQuestionToCaseInvocableApex.Arguments arguments = new MapSurveyQuestionToCaseInvocableApex.Arguments();
        arguments.surveyQuestionList = (List<Survey_Question__c>) JSON.deserialize(sqListJsonString, List<Survey_Question__c>.class);
        arguments.questionResponses = (List<Survey_Question_Response__c>) JSON.deserialize(sqrListJsonString, List<Survey_Question_Response__c>.class);
        List<MapSurveyQuestionToCaseInvocableApex.Arguments> argumentsWrapper= new List<MapSurveyQuestionToCaseInvocableApex.Arguments>();
        argumentsWrapper.add(arguments);
        
        try {
            Test.startTest();
            List<MapSurveyQuestionToCaseInvocableApex.Results> results = MapSurveyQuestionToCaseInvocableApex.mapSurveyQuestionsToCase(argumentsWrapper);
            Test.stopTest();
        } catch (System.QueryException e) {
            System.assert(e != null);
        }
    }

    @IsTest
    static void testNoSurveyQuestionResponseListPassedToInvocableMethod(){
        //List<Survey_Question__c> JSON String 
        String sqListJsonString =   '[{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY3CAK"},"Id":"0Ku01000000CgY3CAK",' +
                                    '"Full_Question_Text__c":"How was your reservation experience?"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY4CAK"},"Id":"0Ku01000000CgY4CAK",' +
                                    '"Full_Question_Text__c":"How likely are you to recommend our services to a colleague?","Question_Type__c":"NPS"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY5CAK"},"Id":"0Ku01000000CgY5CAK",' +
                                    '"Full_Question_Text__c":"Thank you for taking the time to complete this survey. We truly appreciate your feedback, if there are any other comments you ' +
                                    'would like to add we would love to hear from you."},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY6CAK"},"Id":"0Ku01000000CgY6CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  first and last name below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY7CAK"},"Id":"0Ku01000000CgY7CAK",' +
                                    '"Full_Question_Text__c":"If you would like us to contact you, please provide your  email address below:"},' +
                                    '{"attributes":{"type":"Survey_Question__c","url":"/services/data/v58.0/sobjects/Survey_Question__c/0Ku01000000CgY8CAK"},"Id":"0Ku01000000CgY8CAK",' +
                                    '"Full_Question_Text__c":"‘Data protection: Direct Travel will never release your personal details to any company outside Direct Travel for mailing or ' +
                                    'marketing purposes. In this instance, personal details are used for the purposes of collecting feedback on the service you received from ' +
                                    'Direct Travel. Please see our privacy policy at  Privacy &#124; Direct Travel (dt.com) .’"}]';
        MapSurveyQuestionToCaseInvocableApex.Arguments arguments = new MapSurveyQuestionToCaseInvocableApex.Arguments();
        arguments.surveyQuestionList = (List<Survey_Question__c>) JSON.deserialize(sqListJsonString, List<Survey_Question__c>.class);
        List<MapSurveyQuestionToCaseInvocableApex.Arguments> argumentsWrapper= new List<MapSurveyQuestionToCaseInvocableApex.Arguments>();
        argumentsWrapper.add(arguments);
        
        try {
            Test.startTest();
            List<MapSurveyQuestionToCaseInvocableApex.Results> results = MapSurveyQuestionToCaseInvocableApex.mapSurveyQuestionsToCase(argumentsWrapper);
            Test.stopTest();
        } catch (System.NullPointerException e) {
            System.assert(e != null);
        }
    }

    @IsTest
    static void testNosurveyQuestionListPassedToInvocableMethod(){
        //List<Survey_Question_Response__c> JSON String 
        String sqrListJsonString =  '[{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMJCA2"},' + 
                                    '"Id":"0Kr010000004EMJCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY8CAK","Text_Value__c":"I acknowledge"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMKCA2"},' + 
                                    '"Id":"0Kr010000004EMKCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY4CAK","Number_Value__c":1,"Text_Value__c":"1"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMLCA2"},' +
                                    '"Id":"0Kr010000004EMLCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY6CAK","Text_Value__c":"Mike Masters"},' + 
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMMCA2"},' +
                                    '"Id":"0Kr010000004EMMCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY5CAK","Text_Value__c":"Nothing"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMNCA2"},' +
                                    '"Id":"0Kr010000004EMNCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY3CAK","Text_Value__c":"Low Score, Email Provided"},' +
                                    '{"attributes":{"type":"Survey_Question_Response__c","url":"/services/data/v58.0/sobjects/Survey_Question_Response__c/0Kr010000004EMOCA2"},' +
                                    '"Id":"0Kr010000004EMOCA2","Legacy_Response_Id__c__c":"0My010000004ExMCAU","Survey_Question__c":"0Ku01000000CgY7CAK","Text_Value__c":"t@t.com"}]';
        MapSurveyQuestionToCaseInvocableApex.Arguments arguments = new MapSurveyQuestionToCaseInvocableApex.Arguments();
        arguments.questionResponses = (List<Survey_Question_Response__c>) JSON.deserialize(sqrListJsonString, List<Survey_Question_Response__c>.class);
        List<MapSurveyQuestionToCaseInvocableApex.Arguments> argumentsWrapper= new List<MapSurveyQuestionToCaseInvocableApex.Arguments>();
        argumentsWrapper.add(arguments);
        
        try {
            Test.startTest();
            List<MapSurveyQuestionToCaseInvocableApex.Results> results = MapSurveyQuestionToCaseInvocableApex.mapSurveyQuestionsToCase(argumentsWrapper);
            Test.stopTest();
        } catch (System.NullPointerException e) {
            System.assert(e != null);
        }
    }
}