objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RegionG</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <description>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</description>
        <inlineHelpText>Enter the year which represents the travel volumes entered in this section. Note: this is a calendar year!</inlineHelpText>
        <label>Reported Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2019 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2018 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2017 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2016 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2015 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2014 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2013 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2012 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2011 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2010 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2009 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2008 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2007 - Calendar Year</fullName>
                </value>
                <value>
                    <fullName>2007 - Customer&apos;s Fiscal</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2020 - Calendar Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Account_Number__c.object
<CustomObject>
    <label>Account Number</label>
    <nameField>
        <displayFormat>AN-{0000000}</displayFormat>
        <label>Account Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Numbers</relationshipLabel>
        <relationshipName>Account_Number</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/DK_Volume__c.object
<CustomObject>
    <label>DK Travel Volume</label>
    <nameField>
        <displayFormat>DK-{00000000}</displayFormat>
        <label>DK Volume</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DK Travel Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Travel_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <label>Reported Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Volume__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Travel Volume</label>
        <referenceTo>Travel_Volume__c</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Travel_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number Name</label>
        <referenceTo>Account_Number__c</referenceTo>
        <relationshipLabel>DK Travel Volumes</relationshipLabel>
        <relationshipName>DK_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reported_Month__c</fullName>
        <label>Reported Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Travel_Volume__c.object
<CustomObject>
    <description>Stores the account travel volumes from back office</description>
    <label>Travel Volume</label>
    <nameField>
        <displayFormat>TV-{0000000}</displayFormat>
        <label>Travel Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Volumes</relationshipLabel>
        <relationshipName>Travel_Volumes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reported_Year__c</fullName>
        <label>Reported Year</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reported_Month__c</fullName>
        <label>Reported Month</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/addupdateTravelVolumeTest.cls
@isTest
private class addupdateTravelVolumeTest {
    @isTest static void TestUpdate() {
        // Test data setup
        // Create an account with an opportunity, and then try to delete it
        // 
        Account acct = new Account(Name='Test Account', Type='Central Client', Region__c='Central', AccountSource='ATPI', Industry='Accounting');
        insert acct;
        
        Account_Number__c acctNum = new Account_Number__c(Account__c=acct.ID, Account_Number__c='1234567890');
        insert acctNum;
        
        Travel_Volume__c tvol = new Travel_Volume__c(Account__c=acct.id, Reported_Month__c='01', Reported_Year__c='2020');
        insert tvol;
        
        DK_Volume__c dkvol = new DK_Volume__c(Account_Number__c=acctNum.ID, Reported_Month__c='01', Reported_Year__c='2020');
        insert dkvol;
   
    }
    
}