objects/Survey__c.object
<CustomObject>
    <description>Custom survey object built to expand functionality beyond the native Salesforce Survey model.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description of Survey__c record.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Survey_Invitation__c.object
<CustomObject>
    <description>Custom Survey Invitation object designed to replace the native Salesforce Surveys SurveyInvitation object. Survey Invitations represent an instance of a survey generated and sent to a user (via URL) to take.</description>
    <label>Survey Invitation</label>
    <nameField>
        <label>Survey Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey__c record in use for this Survey Invitation.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <description>Custom Survey_Question__c object that allows more customization than the native Salesforce Surveys solution. The Survey Question object represents an instance of a question that is presented to a survey respondent as part of a Survey. Every Survey Question record relates to a Survey record.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Looks up to the Survey this Survey Question relates to.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the survey question.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>RadioButton</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>ShortText</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Question_Text__c</fullName>
        <description>The name of the Survey Question record is truncated at 255 characters. This field stores the full question text, up to 32,768 characters. This is the text that should be displayed to the end survey respondent when taking a survey.</description>
        <label>Full Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Survey_Question_Response__c.object
<CustomObject>
    <description>Custom object built as part of a solution to deliver functionality beyond native Salesforce Surveys. Survey Question Responses relate to Survey_Question__c records, which in turn relate to a Survey__c record. This object specifically stores the responses submitted for a survey.</description>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000000000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Text_Value__c</fullName>
        <description>Response provided by a participant for a question.</description>
        <label>Text Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <description>Response provided by a participant for the following question types:
Net Promoter Score (NPS)
Rating
Score
Slider</description>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Lookup to the Survey Question this record is in response to.</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Survey Response record represents the overall submitted responses by a respondent for a survey invitation.</description>
        <inlineHelpText>Anytime a Survey Invitation link is clicked on, a Survey Response record is generated, even if the responses are not completed. A Survey Response therefore represents the overall status of a respondent&apos;s survey responses - Complete Survey Responses mean all required questions had answers submitted; Started means a link was clicked on but the Survey was not completed.</inlineHelpText>
        <label>Survey Response</label>
        <referenceTo>Survey_Response__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Survey Invitation record related to this Survey Question Response.</description>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <description>Represents information about a participant’s collective responses to a survey. Part of custom survey solution that replaced native Salesforce Surveys solution.</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey in play for this Survey Response record.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey Invitation related to this survey response.</description>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/SurveyController_Test.cls
/**
 * Created by zacox on 7/17/24.
 */

@IsTest
private class SurveyController_Test {

    @TestSetup
    static void setup() {
        // Create a Survey record
        Survey__c survey = new Survey__c(
                Name = 'Customer Satisfaction Survey',
                Description__c = 'A survey to gauge customer satisfaction.'
        );
        insert survey;

        // Create a Survey Invitation record and link it to the Survey
        Survey_Invitation__c invitation = new Survey_Invitation__c(
                Survey__c = survey.Id
        );
        insert invitation;

        // Create Survey Question records and link them to the Survey
        Survey_Question__c question1 = new Survey_Question__c(
                Survey__c = survey.Id,
                Name = 'Q1',
                Question_Type__c = 'FreeText',
                Full_Question_Text__c = 'How satisfied are you with our service?'
        );

        Survey_Question__c question2 = new Survey_Question__c(
                Survey__c = survey.Id,
                Name = 'Q2',
                Question_Type__c = 'FreeText',
                Full_Question_Text__c = 'Please provide any additional feedback.'
        );

        // Insert the Survey Question records
        insert new List<Survey_Question__c>{question1, question2};
    }

    @IsTest
    static void testGetSurveyInfo() {
        Survey_Response__c surveyResponse = new Survey_Response__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id
        );
        insert surveyResponse;

        String surveyInfoJSON = SurveyController.getSurveyInfo(surveyResponse.Id);
        SurveyController.SurveyInfo info = (SurveyController.SurveyInfo) JSON.deserialize(surveyInfoJSON, SurveyController.SurveyInfo.class);

        System.assertEquals(2, info.questions.size());
        System.assertEquals(surveyResponse.Id, info.surveyResponse.Id);
    }

    @IsTest
    static void testSubmitNPSResponse() {
        Survey_Response__c surveyResponse = new Survey_Response__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id,
                Survey_Invitation__c = [SELECT Id FROM Survey_Invitation__c LIMIT 1].Id
        );
        insert surveyResponse;

        Survey_Question__c question = new Survey_Question__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id,
                Name = 'Q1',
                Question_Type__c = 'NPS',
                Full_Question_Text__c = 'How likely are you to recommend us to a friend?'
        );
        insert question;

        String responsesPayload = JSON.serialize(new SurveyController.ResponseMap(question.Id, '9'));
        SurveyController.submitNPSResponse(responsesPayload, surveyResponse.Id);

        Survey_Question_Response__c response = [
                SELECT Id, Survey_Question__c, Text_Value__c, Number_Value__c
                FROM Survey_Question_Response__c
                WHERE Survey_Response__c =: surveyResponse.Id
        ];

        System.assertEquals('9', response.Text_Value__c);
        System.assertEquals(9, response.Number_Value__c.intValue());
    }

    @IsTest
    static void testSubmitResponses() {
        Survey_Response__c surveyResponse = new Survey_Response__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id,
                Survey_Invitation__c = [SELECT Id FROM Survey_Invitation__c LIMIT 1].Id
        );
        insert surveyResponse;

        Survey_Question__c question1 = new Survey_Question__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id,
                Name = 'Q1',
                Question_Type__c = 'FreeText',
                Full_Question_Text__c = 'How satisfied are you with our service?'
        );

        Survey_Question__c question2 = new Survey_Question__c(
                Survey__c = [SELECT Id FROM Survey__c LIMIT 1].Id,
                Name = 'Q2',
                Question_Type__c = 'FreeText',
                Full_Question_Text__c = 'Please provide any additional feedback.'
        );

        insert new List<Survey_Question__c>{question1, question2};

        String responsesPayload = JSON.serialize(new SurveyController.QuestionResponses(
                new List<SurveyController.ResponseMap>{
                        new SurveyController.ResponseMap(question1.Id, 'Very satisfied', 'String'),
                        new SurveyController.ResponseMap(question2.Id, 'Great service!', 'String')
                }
        ));

        SurveyController.submitResponses(responsesPayload, surveyResponse.Id);

        List<Survey_Question_Response__c> responses = [
                SELECT Id, Survey_Question__c, Text_Value__c
                FROM Survey_Question_Response__c
                WHERE Survey_Response__c =: surveyResponse.Id
        ];

        System.assertEquals(2, responses.size());
        System.assertEquals('Very satisfied', responses[0].Text_Value__c);
        System.assertEquals('Great service!', responses[1].Text_Value__c);
    }
}