objects/Survey__c.object
<CustomObject>
    <description>Custom survey object built to expand functionality beyond the native Salesforce Survey model.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Survey_Invitation__c.object
<CustomObject>
    <description>Custom Survey Invitation object designed to replace the native Salesforce Surveys SurveyInvitation object. Survey Invitations represent an instance of a survey generated and sent to a user (via URL) to take.</description>
    <label>Survey Invitation</label>
    <nameField>
        <label>Survey Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey__c record in use for this Survey Invitation.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account record related to the survey respondent for this Survey Invitation.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <description>The user Id of the running user taking the Survey__c for this Survey Invitation. Typically the running user will be a guest user for the experience site hosting the Survey__c.</description>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Id__c</fullName>
        <description>Id of the Experience Cloud Site that the Survey Invitation was generated from.</description>
        <label>Community Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invitation_Link__c</fullName>
        <description>Link generated to send respondent to survey page.</description>
        <label>Invitation Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Overall_Survey_Response_Status__c</fullName>
        <description>Mapped to legacy Response Status field from the SurveyInvitation object for native Salesforce Surveys solution.</description>
        <inlineHelpText>Completed means a response to all required questions for this Survey has been submitted, otherwise, the status is Started (invitation link clicked on).</inlineHelpText>
        <label>Overall Survey Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NotStarted</fullName>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Survey_Link__mdt.object
<CustomObject>
    <description>URL Configuration based on Survey and Language</description>
    <label>Survey Link</label>
    <pluralLabel>Survey Links</pluralLabel>
    <fields>
        <fullName>Path__c</fullName>
        <label>Path</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client Traveler Survey</fullName>
                    <default>true</default>
                    <label>Client Traveler Survey</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Domain__c</fullName>
        <label>Sub Directory</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <description>Represents information about a participant’s collective responses to a survey. Part of custom survey solution that replaced native Salesforce Surveys solution.</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NotStarted</fullName>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey in play for this Survey Response record.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Account associated with this Survey Response record.</description>
        <formula>HYPERLINK( &quot;/&quot; &amp; Survey_Invitation__r.Account__c, Survey_Invitation__r.Account__r.Name)</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the survey response record.</description>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey Invitation related to this survey response.</description>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/CreateSurveyLWC_Controller.cls
/**
 * @author Samuel Prada, Rosetree Solutions
 * @website https://rosetreesolutions.com/
 * @email info@RosetreeSolutions.com
 * @phone (214) 731 - 7314
 * @date 05/20/23
 * @description This is a Salesforce Lightning Web Component Controller class. 
 */

 /**
 * @description This LWC controller class is responsible for creating surveys 
 * invitations and returning the link to the invitation.
 */
public without sharing class CreateSurveyLWC_Controller {

    private static Survey__c survey;
    private static Survey_Link__mdt surveyLinkConfig;
    private static Account account;

    private static final Map<String, String> languageMap = new Map<String, String>{
        'en' => 'English',
        'fr' => 'French'
    };

    
    /**
    * @description This method creates a survey invitation for a given 
    * account and returning the link to the invitation.
    * @param accountId String   
    * @param surveyName String
    * @param communityId String
    * @param language String
    * @return String         
    */
	@AuraEnabled
    public static String createSurvey(String accountId, String surveyName, String communityId, String language) {
        validateParameters(accountId,  surveyName,  communityId,  language);
        Survey_Invitation__c invitation = createSurveyInvitation(communityId);
        String surveyResponseId = createSurveyResponse(invitation.Id, language);
        
        // Redirect URL to survey with surveyResponseId
        return invitation.Invitation_Link__c + '?resp=' + surveyResponseId + '&lang=' + language;
    }

    private static void validateParameters(String accountId, String surveyName, String communityId, String language) {
        //Null parameter handling
        if (accountId == null) {
            throw new InvalidParameterException('Parameter \'accountId\' can not be null.');
        } else if(surveyName == null){
            throw new InvalidParameterException('Parameter \'surveyName\' can not be null.');
        } else if(communityId == null){
            throw new InvalidParameterException('Parameter \'communityId\' can not be null.');
        } else if(language == null){
            throw new InvalidParameterException('Parameter \'language\' can not be null.');
        }
        //Invalid parameter handling
        try{
            account = [SELECT Id, Name FROM Account WHERE Id =: accountId];
        } catch (Exception e){
            throw new InvalidParameterException('Invalid Account Id.');
        }
        
        try{
            survey = [SELECT Id, Name, Developer_Name__c FROM Survey__c WHERE Developer_Name__c =: surveyName];
        } catch (System.QueryException e) {
            throw new InvalidParameterException('Invalid Survey name.');
        }

        if(!language.equals('en') && !language.equals('fr')){
            throw new InvalidParameterException('Invalid language parameter.');
        }

        try{
            surveyLinkConfig = [
                    SELECT Language__c, Path__c, Sub_Domain__c
                    FROM Survey_Link__mdt
                    WHERE Survey__c =: survey.Name
                    AND Language__c =: languageMap.get(language)
                    LIMIT 1
            ];
        } catch (System.QueryException e) {
            throw new InvalidParameterException('Could not find Survey Link Config record.');
        }
    }

    private static Survey_Invitation__c createSurveyInvitation(Id communityId) {
        Survey_Invitation__c surveyInv = new Survey_Invitation__c();
        String invitationName = account.Name + ' ' + survey.Name + ' ' + Date.today().format();
        if(invitationName.length() > 80) {
            invitationName = invitationName.substring(0, 80);
        }
        surveyInv.Name = invitationName;
        surveyInv.Community_Id__c = communityId;
        surveyInv.Survey__c = survey.Id;
        surveyInv.Account__c = account.Id;
        surveyInv.Invitation_Link__c = generateSurveyInvitationLink();
        surveyInv.User_Id__c = UserInfo.getUserId();
        surveyInv.Overall_Survey_Response_Status__c = 'Started';
        insert surveyInv;

        return surveyInv;
    }

    private static String generateSurveyInvitationLink() {
        String surveyUrl = Url.getCurrentRequestUrl().toExternalForm();
        surveyUrl = surveyUrl.split('.com/')[0] + '.com/';
        surveyUrl += surveyLinkConfig.Sub_Domain__c + '/' + surveyLinkConfig.Path__c + '/';
        return surveyUrl;
    }

    private static String createSurveyResponse(Id invitationId, String language) {
        Survey_Response__c surveyResponse = new Survey_Response__c();
        surveyResponse.Survey_Invitation__c = invitationId;
        surveyResponse.Language__c = language == 'en' ? 'en_US' : 'fr_CA';
        surveyResponse.Status__c = 'Started';
        surveyResponse.Survey__c = survey.Id;
        insert surveyResponse;
        return surveyResponse.Id;
    }

    @TestVisible
    private class InvalidParameterException extends Exception {}
}