objects/Survey__c.object
<CustomObject>
    <description>Custom survey object built to expand functionality beyond the native Salesforce Survey model.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <description>Brief description of Survey__c record.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Survey_Invitation__c.object
<CustomObject>
    <description>Custom Survey Invitation object designed to replace the native Salesforce Surveys SurveyInvitation object. Survey Invitations represent an instance of a survey generated and sent to a user (via URL) to take.</description>
    <label>Survey Invitation</label>
    <nameField>
        <label>Survey Invitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey__c record in use for this Survey Invitation.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Survey_Response_Status__c</fullName>
        <description>Mapped to legacy Response Status field from the SurveyInvitation object for native Salesforce Surveys solution.</description>
        <inlineHelpText>Completed means a response to all required questions for this Survey has been submitted, otherwise, the status is Started (invitation link clicked on).</inlineHelpText>
        <label>Overall Survey Response Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NotStarted</fullName>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <description>Custom Survey_Question__c object that allows more customization than the native Salesforce Surveys solution. The Survey Question object represents an instance of a question that is presented to a survey respondent as part of a Survey. Every Survey Question record relates to a Survey record.</description>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Looks up to the Survey this Survey Question relates to.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>The data type of the survey question.</description>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>RadioButton</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>ShortText</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Question_Text__c</fullName>
        <description>The name of the Survey Question record is truncated at 255 characters. This field stores the full question text, up to 32,768 characters. This is the text that should be displayed to the end survey respondent when taking a survey.</description>
        <label>Full Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>French_Question_Text__c</fullName>
        <description>Full Question Text - French Translation</description>
        <label>French Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Legacy_SurveyQuestion_Id__c</fullName>
        <description>Before the custom Survey__c object was built, Salesforce Surveys were in use. This field stores the legacy  Id for the corresponding, historical Salesforce Surveys SurveyQuestion record.</description>
        <externalId>true</externalId>
        <label>Legacy SurveyQuestion Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Survey_Question_Response__c.object
<CustomObject>
    <description>Custom object built as part of a solution to deliver functionality beyond native Salesforce Surveys. Survey Question Responses relate to Survey_Question__c records, which in turn relate to a Survey__c record. This object specifically stores the responses submitted for a survey.</description>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>SQR-{0000000000}</displayFormat>
        <label>Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Data_Type__c</fullName>
        <description>The data type of the question response</description>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Int</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>String</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <description>Response provided by a participant for a question.</description>
        <label>Text Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <description>Response provided by a participant for the following question types:
Net Promoter Score (NPS)
Rating
Score
Slider</description>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsTrueorFalse__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Response provided by a participant for a question type which has only two possible values: True and False.</description>
        <label>IsTrueorFalse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <description>Lookup to the Survey Question this record is in response to.</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Survey Response record represents the overall submitted responses by a respondent for a survey invitation.</description>
        <inlineHelpText>Anytime a Survey Invitation link is clicked on, a Survey Response record is generated, even if the responses are not completed. A Survey Response therefore represents the overall status of a respondent&apos;s survey responses - Complete Survey Responses mean all required questions had answers submitted; Started means a link was clicked on but the Survey was not completed.</inlineHelpText>
        <label>Survey Response</label>
        <referenceTo>Survey_Response__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Survey Invitation record related to this Survey Question Response.</description>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Question Responses</relationshipLabel>
        <relationshipName>Survey_Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Completion_DateTime__c</fullName>
        <description>Stores legacy response completion date/time as well as net new records response completion date/time.</description>
        <label>Response Completion Date/Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <description>Represents information about a participant’s collective responses to a survey. Part of custom survey solution that replaced native Salesforce Surveys solution.</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NotStarted</fullName>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey in play for this Survey Response record.</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language of the survey response record.</description>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Invitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Survey Invitation related to this survey response.</description>
        <label>Survey Invitation</label>
        <referenceTo>Survey_Invitation__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completion_Date_Time__c</fullName>
        <description>The date/time the survey response was submitted and completed.</description>
        <label>Completion Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Optional_Feedback_Status__c</fullName>
        <description>Used to control automation (flow) that keys off of survey response object. Indicates if any of the optional fields were filled out on the survey.</description>
        <label>Optional Feedback Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/SurveyController.cls
/**
 * Created by zacox on 5/11/24.
 */

public without sharing class SurveyController {

    @AuraEnabled(Cacheable=true)
    public static String getSurveyInfo(String responseId) {
        Survey__c survey = getSurvey(responseId);
        Survey_Response__c surveyResponse = getSurveyResponse(responseId);
        List<Survey_Question__c> questions = [
                SELECT Id, Name, Question_Type__c, Full_Question_Text__c, French_Question_Text__c
                FROM Survey_Question__c
                WHERE Survey__c =: survey.Id
                AND Legacy_SurveyQuestion_Id__c = NULL
        ];

        return JSON.serialize(new SurveyInfo(questions, surveyResponse));

    }

    private static Survey__c getSurvey(String responseId) {
        Survey_Response__c surveyResponse = [SELECT Survey__c FROM Survey_Response__c WHERE Id =: responseId];
        return [SELECT Id, Name, Description__c FROM Survey__c WHERE Id =: surveyResponse.Survey__c];
    }

    @AuraEnabled
    public static String submitNPSResponse(String responsesPayload, String surveyResponseId) {
        ResponseMap responseMap = (ResponseMap) JSON.deserialize(responsesPayload, ResponseMap.class);

        Survey_Response__c surveyResponse = getSurveyResponse(surveyResponseId);

        Survey_Question_Response__c questionResponse = new Survey_Question_Response__c(
                Survey_Response__c = surveyResponseId,
                Survey_Question__c = responseMap.questionId,
                Survey_Invitation__c = surveyResponse.Survey_Invitation__c,
                Text_Value__c = responseMap.responseValue,
                Number_Value__c = Decimal.valueOf(responseMap.responseValue),
                Data_Type__c = 'String',
                Response_Completion_DateTime__c = Datetime.now()
        );
        insert questionResponse;

        Survey_Invitation__c surveyInvitation = [SELECT Id FROM Survey_Invitation__c WHERE Id =: surveyResponse.Survey_Invitation__c];
        surveyInvitation.Overall_Survey_Response_Status__c = 'Completed';
        update surveyInvitation;

        surveyResponse.Status__c = 'Completed';
        surveyResponse.Completion_Date_Time__c = Datetime.now();
        update surveyResponse;

        return 'Success';
    }

    @AuraEnabled
    public static String submitResponses(String responsesPayload, String surveyResponseId) {
        QuestionResponses responses = (QuestionResponses) JSON.deserialize(responsesPayload, QuestionResponses.class);
        Survey_Response__c surveyResponse = getSurveyResponse(surveyResponseId);
        List<Survey_Question_Response__c> responsesToInsert = new List<Survey_Question_Response__c>();

        System.debug('responses: ' + JSON.serialize(responses));

        for(ResponseMap responseMap : responses.responses) {

            Survey_Question_Response__c questionResponse = new Survey_Question_Response__c(
                    Survey_Response__c = surveyResponseId,
                    Survey_Question__c = responseMap.questionId,
                    Survey_Invitation__c = surveyResponse.Survey_Invitation__c,
                    Data_Type__c = responseMap.dataType,
                    Response_Completion_DateTime__c = Datetime.now()
            );
            if(responseMap.dataType == 'String') {
                questionResponse.Text_Value__c = responseMap.responseValue;
            } else if(responseMap.dataType == 'Number') {
                questionResponse.Number_Value__c = Decimal.valueOf(responseMap.responseValue);
            } else if(responseMap.dataType == 'Boolean') {
                questionResponse.IsTrueorFalse__c = responseMap.responseValue == responseMap.responseValue;
                questionResponse.Text_Value__c = responseMap.responseValue;
            } else if(responseMap.dataType == 'Int') {
//                questionResponse.Date_Value__c = Date.valueOf(responseMap.responseValue);
            }
            responsesToInsert.add(questionResponse);
        }

        System.debug('responsesToInsert: ' + JSON.serialize(responsesToInsert));

        if(!responsesToInsert.isEmpty()) {
            insert responsesToInsert;
        }

        surveyResponse.Optional_Feedback_Status__c = 'Completed';
        update surveyResponse;

        return 'Success';
    }


    private static Survey_Response__c getSurveyResponse(String responseId) {
        Survey_Response__c surveyResponse = [
                SELECT Id, Survey__c, Language__c, Status__c, Survey_Invitation__c
                FROM Survey_Response__c
                WHERE Id =: responseId
        ];
        return surveyResponse;
    }

    public class ResponseMap {
        @AuraEnabled
        public String questionId { get; set; }
        @AuraEnabled
        public String responseValue { get; set; }
        @AuraEnabled
        public String dataType { get; set; }

        public ResponseMap(String questionId, String responseValue) {
            this.questionId = questionId;
            this.responseValue = responseValue;
            this.dataType = 'String;';
        }

        public ResponseMap(String questionId, String responseValue, String dataType) {
            this.questionId = questionId;
            this.responseValue = responseValue;
            this.dataType = dataType;
        }
    }

    public class QuestionResponses {
        @AuraEnabled
        public List<ResponseMap> responses  { get; set; }

        public QuestionResponses(List<ResponseMap> responses) {
            this.responses = responses;
        }
    }

    public class SurveyInfo {
        @AuraEnabled
        public List<Survey_Question__c> questions { get; set; }
        @AuraEnabled
        public Survey_Response__c surveyResponse { get; set; }

        public SurveyInfo(List<Survey_Question__c> questions, Survey_Response__c survey) {
            this.questions = questions;
            this.surveyResponse = survey;
        }
    }
}